version: '3.8' # Docker Compose 버전

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: es01
    environment:
      - discovery.type=single-node # 단일 노드로 실행
      - xpack.security.enabled=false # X-Pack 비활성화 (개발 편의를 위해 보안 기능 비활성화)
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # 메모리 설정
    ports:
      - "9200:9200" # 호스트의 9200 포트와 컨테이너의 9200 포트 연결
      - "9300:9300" # 호스트의 9300 포트와 컨테이너의 9300 포트 연결
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kib01
    environment:
      - ELASTICSEARCH_HOST=http://es01:9200 # Kibana가 연결할 Elasticsearch 주소
    ports:
      - "5601:5601" # 호스트의 5601 포트와 컨테이너의 5601 포트 연결
    depends_on:
      - elasticsearch
    networks:
      - elastic

networks:
  elastic:
    driver: bridge